FROM oven/bun:1

WORKDIR /app

COPY package.json bun.lock ./
COPY proto ./proto/
COPY src ./src/
COPY tsconfig.json ./
COPY .env ./

RUN bun install

RUN bun install

EXPOSE 3001 4001

CMD ["bun", "src/main.ts"]